services:
  transcripto-bot:
    image: transcripto-app
    container_name: transcripto-bot
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env
    env_file:
      - .env
    command: python -m transcripto --telegram-bot
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: "4.0"
