services:
  transcripto-bot:
    image: transcripto-app
    container_name: transcripto-bot
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env
    env_file:
      - .env
    command: python -m transcripto --telegram-bot
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 8g
          cpus: "4.0"
